[package]
name = "live-oscilloscope"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.3.11", features = ["derive"] }
eframe = { version = "0.22.0", features = ["serde"] }
portaudio-rs = "0.3.2"
